### ISSUE TITLE
Missing export

### ISSUE THREAD

**Issue by Zipheir** [diamond-lizard/srfi-160#2]
`list->@vector` should be exported by each `(srfi 160 @)`, but it is currently only exported by `(srfi 160 base)`.

**Comment by diamond-lizard** [comment]
I don't understand how [this test](https://github.com/diamond-lizard/srfi-160/blob/751bf717903ad384171c318eeb2cbb92ae81721e/tests/shared-tests.scm#L198) could have passed if ```list->@vector``` wasn't exported.

Also, I'm puzzled as to why it's expecting a list of integers.  Shouldn't it be expecting a vector?

**Comment by Zipheir** [comment]
I'm guessing that `chicken-install -test` is including the base library as well as the `s16` library. Running the tests manually from `csi` gives:

`Error: unbound variable: list->s16vector
        (s16vector->list (list->s16vector '(1 2 3 4 5)))`

As for the list of integers, isn't this what you'd expect as an argument to `list->s16vector`?

**Comment by diamond-lizard** [comment]
It looks like ```list->@vector``` came from SRFI-4, and the mystery test was passing due to SRFI-160 defining [its own test-equiv procedure](https://github.com/diamond-lizard/srfi-160/blob/751bf717903ad384171c318eeb2cbb92ae81721e/tests/shared-tests.scm#L14) which converted the value it was testing using ```s16vector->list```, therefore allowing the value it was comparing to to also be a list.

**Comment by diamond-lizard** [comment]
Fixed in commit https://github.com/diamond-lizard/srfi-160/commit/7c5782fd1603cfc12eea605ae0343d9c74be2d26
